### ISSUE TITLE
Can't work on openwrt plantform

### ISSUE THREAD

**Issue by Hinata-official** [Caian/xinfc#1]
![image](https://github.com/Caian/xinfc/assets/61258915/6478eb71-4603-4c68-beec-b00e7e89bbf7)
I use your tool to config my ax3000t,but when i use this tool ,it doesn't work on my device
![image](https://github.com/Caian/xinfc/assets/61258915/4341b919-1579-4876-b39e-85fef125bd2a)
this is my device's system information,i don't know what's this ,i don't have any device to compile source code,is this compile error or some other problems.
i already installed i2c-tools

**Comment by Caian** [comment]
Hi, you seem to be running openwrt 21. My release was built using openwrt 23. I may be able to make it compatible if I find a source for that release.

**Comment by Caian** [comment]
@Hinata-official could you print the output of the following command?

```
ldd xinfc-wsc
```

Thank you

**Comment by Hinata-official** [comment]
> ldd xinfc-wsc

![image](https://github.com/Caian/xinfc/assets/61258915/818e4420-bcc2-45eb-a31e-68872d530fa9)
this is my reply,could this can help you?

**Comment by Hinata-official** [comment]
> @Hinata-official could you print the output of the following command?
> 
> ```
> ldd xinfc-wsc
> ```
> 
> Thank you

https://drive.google.com/file/d/1OlH-voUpGLbZscSCUxn-5KKLtKg82aK2/view?usp=drive_link
this is my firmware,i think it might can help you.

**Comment by Hinata-official** [comment]
> @Hinata-official could you print the output of the following command?
> 
> ```
> ldd xinfc-wsc
> ```
> 
> Thank you

this firmware only have Chinese UI ,SSH username is root,password is blank,router default ip address is 172.31.0.1.

**Comment by Caian** [comment]
@Hinata-official Please, see if this build works.

[xinfc_2024-01-29_immortalwrt21.02_ax3000t.zip](https://github.com/Caian/xinfc/files/14144114/xinfc_2024-01-29_immortalwrt21.02_ax3000t.zip)

**Comment by Hinata-official** [comment]
> @Hinata-official请看看这个构建是否有效。
> 
> [xinfc_2024-01-29_immortalwrt21.02_ax3000t.zip](https://github.com/Caian/xinfc/files/14144114/xinfc_2024-01-29_immortalwrt21.02_ax3000t.zip)

![image](https://github.com/Caian/xinfc/assets/61258915/dac6ffb1-b48a-4b27-b86e-0c7be6dffee7)
it worked!!!!THANK YOU!!!!!!!!!!!!!!!!And i think you can notice that wpa2-psk + eas should use psk2+aes,some users like me have to try lots of times to find a correct encryption method can work.
![image](https://github.com/Caian/xinfc/assets/61258915/f23a572d-8e7c-4c54-8ee9-7faec6ee2209)
and i found a place seems a bug,when i use wrong encryption method,the tools reply a wrong i2c address,is this a bug?
In the end ,THANK YOU FOR your tool and Chinese Lunar New Year is coming , here is my New Year Wish for you ,HOPE YOU CAN MAKE MORE USEFUL PROJECT TO THIS WORLD ,thanks, :D

**Comment by Caian** [comment]
Hi @Hinata-official I see that you called xinfc with "0x87" instead of "0x57". The address is the decimal value of the hex "0x87", while 87 is the decimal value of "0x57" (I should change that for clarity).

Just a friendly reminder that the encryption is case sensitive.

Thank you, and Happy Chinese Lunar New Year for you too!

**Comment by Hinata-official** [comment]
> 你好@Hinata-official我看到您用“0x87”而不是“0x57”调用 xinfc。地址是十六进制“0x87”的十进制值，而87是“0x57”的十进制值（为了清楚起见，我应该更改它）。
> 
> 只是友情提醒，加密是区分大小写的。
> 
> 谢谢您，也祝您农历新年快乐！

oh,i know,THANK YOU!
